FROM node:20-alpine

WORKDIR /user/src/app

ARG DATABASE_URL 


# having multiple package.json optimisation goes hactic

COPY ./packages ./packages
COPY ./.npmrc ./.npmrc 

COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json
COPY ./README.md ./README.md
COPY ./apps/web ./apps/web

RUN pnpm install
RUN pnpm run db:generate
RUN  DATABASE_URL={DATABASE_URL} run build

EXPOSE 3000

CMD [ "pnpm","run","start:web" ]