name: Deploying to Staging Server

on:
  push:
    branches:
      - production

jobs:
  redeploy_everything:
    name: Redeploy Backend and Frontend on Staging Server
    runs-on: ubuntu-latest

    steps:
      - name: Decode SSH Private Key
        run: | 
          echo "${{secrets.SSH_PRIVATE_KEY}}" &> ~/ssh_key
          chmod 600 ~/ssh_key

      - name: SSH into Server and Redeploy
        run: |
          ssh -i ~/ssh_key -o StrictHostKeyChecking=no ubuntu@13.60.92.155 << 'EOF'
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            export PATH=$NVM_DIR/versions/node/v18.20.8/bin:$PATH
            cd Devops
            git pull origin production
            cd day-25/2/bms
            pnpm installw
            pnpm run build
            pm2 restart all
          EOF
