name : Deploying to Staging Server
on:
  push:
    branches:
      - main

jobs:
    redeploy_everything :
        name : Redeploy Frontend on  Staging Server
        runs-on : ubuntu-latest

        steps : 
            - name: SSH into server
              run: |
                echo "${SSH_PRIVATE_KEY}" > ~/ssh_key
                chmod 600 ~/ssh_key
                ssh -i ~/ssh_key -o StrictHostKeyChecking=no ubuntu@51.20.53.226 << 'EOF'
                  cd Devops
                  git pull origin main
                  cd day-25/2/bms
                  pnpm install
                  pnpm run build
                  pm2 restart all
                EOF


