version : '3.8'
services:
  postgres :
    image : postgres:latest
    restart : always
    environment :
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : password
    ports :
      - "5432:5432"
  user_app:
    build:
      context : ./
      dockerfile : Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/postgres"
    ports:
      - "3000:3000"